version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ROOT
      POSTGRES_PASSWORD: password
      POSTGRES_DB: online_store
    ports:
      - 5433

  redis:
    image: redis
    environment:
      REDIS_PASSWORD: ""
      REDIS_DB: 0
    ports:
      - 6379
